---
- hosts: all

  vars:
    git_user_name: "first middle last"
    git_user_email: "user@example.com"

  tasks:
    - name: install git
      ansible.builtin.dnf:
        name: git
        state: latest
      become: true
    - name: git user name
      community.general.git_config:
        name: user.name
        scope: global
        value: "{{ git_user_name }}"
    - name: git user email
      community.general.git_config:
        name: user.email
        scope: global
        value: "{{ git_user_email }}"
